pull_request_rules:
  - name: automatic approve dependabot pull requests
    conditions:
      - author~=dependabot\[bot\]|dependabot-preview\[bot\]
      - status-success=Travis CI - Pull Request
    actions:
      review:
        type: APPROVE

  - name: automatic merge for dependabot pull requests
    conditions:
      - author~=dependabot\[bot\]|dependabot-preview\[bot\]
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
