name: Run test jobs
on:
  pull_request:

concurrency:
  group: test-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: plus3it/actions-workflows/.github/workflows/test.yml@0a03f75193a010b3532cc90e8ad0b15a09ed33c1
